[miscellaneous]
autoUpdate = false

[gameplay]
speed = 1
replayType = "NanoChart"
needTimeRound = true
[gameplay.offset]
note = 0
judgement = 0
[gameplay.bga]
video = false
image = true
[gameplay.time]
prepare = 2
playPause = 0.2
pausePlay = 0.5
playRetry = 0.5
pauseRetry = 0.5

[graphics]
fps = 240
cursor = "circle"
[graphics.dim]
select = 0.5
gameplay = 0.8
result = 0.6
[graphics.blur]
select = 0
gameplay = 0
result = 0
[graphics.perspective]
camera = false
rx = false
ry = true
x = 0
y = 0
z = 0
pitch = 0
yaw = 0
[graphics.mode]
[graphics.mode.window]
width = 1280
height = 720
[graphics.mode.flags]
fullscreen = false
fullscreentype = "desktop"
vsync = 1

[audio]
[audio.volume]
master = 1
music = 1
effects = 1
[audio.mode]
primary = "streamMemoryTempo"
secondary = "sample"
preview = "streamOpenAL"
[audio.midi]
constantVolume = false

[input]
pause = "escape"
skipIntro = "space"
quickRestart = "`"
selectRandom = "f2"
[input.playSpeed]
decrease = "f3"
increase = "f4"
invert = "f2"
[input.timeRate]
decrease = "f5"
increase = "f6"
invert = "f7"
[input.screenshot]
capture = "f12"
open = "lshift"
