[general]
speed = 1
fps = 240
theme = "userdata/themes/new"
replayType = "NanoChart"
adjustDifficultyAccuracy = 26
adjustDifficultyPerformance = 300
timeToPrepare = 2
inputOffset = 0
visualOffset = 0
needTimeRound = 1
videobga = false
imagebga = true
autoUpdate = false

[graphics]
dimSelect = 0.5
dimGameplay = 0.75
dimResult = 0.75

[audio]
primaryAudioMode = "streamMemoryTempo"
secondaryAudioMode = "sample"
previewAudioMode = "streamOpenAL"
volumeGlobal = 1
volumeMusic = 1
volumeEffects = 1
midiConstantVolume = false

[perspective]
camera = false
allowRotateX = false
allowRotateY = true
x = 0
y = 0
z = 0
pitch = 0
yaw = 0

[input]
pause = "escape"
skipIntro = "space"
quickRestart = "`"
invertPlaySpeed = "f2"
decreasePlaySpeed = "f3"
increasePlaySpeed = "f4"
invertTimeRate = "f7"
decreaseTimeRate = "f5"
increaseTimeRate = "f6"
selectRandomNoteChartSet = "f2"
adjustDifficulty = "f3"
screenshotCapture = "f12"
screenshotOpen = "lshift"
